name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    name: "CI/CD"
    runs-on: defi-dex-linux-medium
    environment: testnet
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ['20.x']

    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install Yarn
        run: npm install --global yarn

      - name: Cache Yarn Dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Compile
        run: yarn run compile

      - name: Run Tests
        run: yarn run test
        
      - name: Extract and publish ABIs
        run: |
            mkdir -p data/abis
            find ./artifacts/contracts -type f -name "*.json" ! -name "*.dbg.json" -exec cp {} data/abis/ \;

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v6.1.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: ${{ secrets.GPG_KEY_ID }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          cwd: "."
          author_name: ${{ secrets.AUTOCOMMIT_GIT_USER_NAME }}
          author_email: ${{ secrets.AUTOCOMMIT_GIT_USER_EMAIL }}
          commit: --signoff
          message: "chore: extract ABI files [autocomit]"
          push: true