name: UpKeeper Cron Job

on:
  schedule:
    - cron: '1/10 * * * *' # every 10 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  upkeeper-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Kepper Function
        run: |
          curl -X POST ${{ secrets.NETLIFY_FUNCTION_URL }} \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n"
        
      - name: Log Result
        if: always()
        run: |
          echo "Schedule check completed at $(date)"
          echo "Check the Netlify function logs for detailed results" 
